name: Publish NuGet package and create GitHub release

on:
  push:
    tags:
      - v*

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore packages
        run: dotnet restore
      - name: Build project
        run: dotnet build --no-restore -c Release
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Package project
        run: dotnet pack --no-build -c Release
      - name: Publish package
        run: dotnet nuget push JKMP.Core/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
      - name: Package artifact
        uses: vimtor/action-zip@v1
        with:
          files: >
            JKMP.Core/bin/Release/net462/JKMP.Core.dll
            JKMP.Core/bin/Release/net462/Serilog.dll
            JKMP.Core/bin/Release/net462/Serilog.Expressions.dll
            JKMP.Core/bin/Release/net462/Serilog.Sinks.Console.dll
            JKMP.Core/bin/Release/net462/Serilog.Sinks.File.dll
            JKMP.Core/bin/Release/net462/Serilog.Enrichers.Demystifier.dll
            JKMP.Core/bin/Release/net462/Ben.Demystifier.dll
            JKMP.Core/bin/Release/net462/0Harmony.dll
            JKMP.Core/bin/Release/net462/Semver.dll
            JKMP.Core/bin/Release/net462/Newtonsoft.Json.dll
            JKMP.Core/bin/Release/net462/Facepunch.Steamworks.Win32.dll
            JKMP.Core/bin/Release/net462/System.Collections.Immutable.dll
          dest: out/JKMP.Core.zip
      - name: Set tag output
        id: tag-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: (v[0-9]+\.[0-9]+\.[0-9]+)(?:-(.+))?$
      - name: Create prerelease (if tag allows it)
        uses: ncipollo/release-action@v1
        if: ${{ steps.tag-match.outputs.group2 != '' }} # Tag has a -prerelease (or other) suffix
        with:
          name: Modular prerelease
          artifacts: out/JKMP.Core.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          generateReleaseNotes: true
          prerelease: true
      - name: Create release (if tag allows it)
        uses: ncipollo/release-action@v1
        if: ${{ steps.tag-match.outputs.group2 == '' }} # Tag has no -prerelease (or other) suffix
        with:
          name: Modular release
          artifacts: out/JKMP.Core.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          generateReleaseNotes: true